# Config

In [44]:
import pandas as pd
import openpyxl
import re
from config import RAW_DATA_DIR, PROCESSED_DATA_DIR
pd.set_option('future.no_silent_downcasting', True)

# Read data

In [45]:
file_path = RAW_DATA_DIR / "FCTAES_279691_TOTAL_20251006.xlsx"

labels_df = pd.read_excel(file_path, sheet_name="Labels")
variables_df = pd.read_excel(file_path, sheet_name="Variables")
codes_df = pd.read_excel(file_path, sheet_name="Codes")

print("Labels",labels_df.shape)
print("Variables",variables_df.shape)
print("Codes",codes_df.shape)

Labels (1813, 514)
Variables (515, 4)
Codes (2442, 3)

# Clean data

## Manage wrong headers

In [46]:
# In codes_df, the first row is actually the header, so we need to clean that up
codes_df = codes_df.drop(index=0).reset_index(drop=True)
codes_df.columns = ["Variable", "Code", "Label"]
print("Cleaned Codes", codes_df.shape)
codes_df.head()

Cleaned Codes (2441, 3)

          Variable Code      Label
0           SAMPLE    1   INTERNAL
1              NaN    2   EXTERNAL
2              NaN    3    TESTING
3              NaN    4       BBDD
4  SAMPLE_PROVIDER    1  NICEQUEST

In [47]:
# delete last row of variables_df
variables_df.drop(variables_df.index[-1], inplace=True)
variables_df.reset_index(drop=True, inplace=True)
variables_df.tail()

,Variable,Posición,Etiqueta,Nivel de medición
509,P91_cod2,510.0,How safe or unsafe would you feel using the ex...,Nominal
510,P91_cod3,511.0,How safe or unsafe would you feel using the ex...,Nominal
511,P91_cod4,512.0,How safe or unsafe would you feel using the ex...,Nominal
512,P91_cod5,513.0,How safe or unsafe would you feel using the ex...,Nominal
513,P91_cod6,514.0,How safe or unsafe would you feel using the ex...,Nominal

## Manage NaN

In [48]:
codes_df['Variable'] = codes_df['Variable'].ffill()
codes_df.head()

          Variable Code      Label
0           SAMPLE    1   INTERNAL
1           SAMPLE    2   EXTERNAL
2           SAMPLE    3    TESTING
3           SAMPLE    4       BBDD
4  SAMPLE_PROVIDER    1  NICEQUEST

# Process Data (Get results)

## 1. Build code dictionary

In [49]:
code_dict = {}

for _, row in codes_df.iterrows():
    var = row["Variable"]
    code = row["Code"]
    label = row["Label"]

    code_dict.setdefault(var, {})[code] = label
code_dict

{'SAMPLE': {'1': 'INTERNAL', '2': 'EXTERNAL', '3': 'TESTING', '4': 'BBDD'},
 'SAMPLE_PROVIDER': {'1': 'NICEQUEST',
  '2': 'Partner_2',
  '3': 'Partner_3',
  '4': 'Partner_4',
  '5': 'Partner_5',
  '6': 'Partner_6',
  '7': 'Partner_7',
  '8': 'Partner_8',
  '9': 'Partner_9',
  '10': 'Partner_10',
  '11': 'Partner_11',
  '12': 'Partner_12',
  '13': 'Partner_13',
  '14': 'Partner_14',
  '15': 'Partner_15',
  '16': 'Partner_16',
  '17': 'Partner_17',
  '18': 'Partner_18',
  '19': 'Partner_19',
  '20': 'Partner_20',
  '21': 'Partner_21',
  '22': 'Partner_22',
  '23': 'Partner_23',
  '24': 'Partner_24',
  '25': 'Partner_25',
  '26': 'Partner_26',
  '27': 'Partner_27',
  '28': 'Partner_28',
  '29': 'Partner_29',
  '30': 'Partner_30',
  '31': 'Partner_31',
  '32': 'Partner_32',
  '33': 'Partner_33',
  '34': 'Partner_34',
  '35': 'Partner_35',
  '36': 'Partner_36',
  '37': 'Partner_37',
  '38': 'Partner_38',
  '39': 'Partner_39',
  '40': 'Partner_40',
  '41': 'Partner_41',
  '42': 'Partner_42',
  '43': 'Partner_43',
  '44': 'Partner_44',
  '45': 'Partner_45',
  '46': 'Partner_46',
  '47': 'Partner_47',
  '48': 'Partner_48',
  '49': 'Partner_49',
  '555': 'Partner_555',
  '666': 'Partner_666',
  '888': 'BBDD',
  '999': 'Partner_999'},
 'SURVEY_COUNTRY': {'1': 'Spain',
  '2': 'Italy',
  '3': 'Denmark',
  '4': 'UK',
  '5': 'Greece'},
 'DEVICE': {'1': 'Desktop', '2': 'Tablet', '3': 'Mobile'},
 'SEXO': {'1': 'Male', '2': 'Female', '3': 'Prefer not to say', '4': 'Other'},
 'EDADR': {'1': '0_15', '2': '16_+'},
 'CITY_ES': {'1': 'Barcelona',
  '2': 'Madrid',
  '3': 'Valencia',
  '4': 'Sevilla',
  '5': 'Zaragoza',
  '6': 'MÃ¡laga',
  '7': 'Murcia',
  '96': 'Otra'},
 'CITY_IT': {'1': 'Roma',
  '2': 'Milano',
  '3': 'Napoli',
  '4': 'Torino',
  '5': 'Firenze',
  '6': 'Bologna',
  '7': 'Palermo',
  '96': 'Altre'},
 'CITY_GB': {'1': 'London',
  '2': 'Birmingham',
  '3': 'Manchester',
  '4': 'Liverpool',
  '5': 'Leeds',
  '6': 'Glasgow',
  '7': 'Edinburgh',
  '96': 'Others'},
 'CITY_DK': {'1': 'Copenhagen',
  '2': 'Aarhus',
  '3': 'Odense',
  '4': 'Aalborg',
  '5': 'Esbjerg',
  '96': 'Others'},
 'CITY_GR': {'1': 'AthÃ\xadna',
  '2': 'ThessalonÃ\xadki',
  '3': 'PÃ¡tra',
  '4': 'IrÃ¡kleio',
  '5': 'LÃ¡risa',
  '6': 'VÃ³los',
  '7': 'IoÃ¡nnina',
  '96': 'Others'},
 'P2#1': {'0': '0', '1': '1'},
 'P2#2': {'0': '0', '1': '1'},
 'P2#3': {'0': '0', '1': '1'},
 'P2#97': {'0': '0', '1': '1'},
 'TRANSPORT_1': {'1': 'Motorcycle/moped - Yes', '2': 'Motorcycle/moped - No'},
 'TRANSPORT_2': {'1': 'Bike or e-bike - Yes', '2': 'Bike or e-bike - No'},
 'TRANSPORT_3': {'1': 'E-scooter - Yes', '2': 'E-scooter - No'},
 'P3#1': {'0': '0', '1': '1'},
 'P3#2': {'0': '0', '1': '1'},
 'P3#3': {'0': '0', '1': '1'},
 'P3#4': {'0': '0', '1': '1'},
 'P4': {'1': 'At least once a day',
  '2': 'At least once a week',
  '3': 'At least once a month',
  '4': 'At least once a year'},
 'P5': {'1': 'Commuting to work',
  '2': 'For recreation / as a hobby',
  '3': 'Shopping, or running errands',
  '4': 'For delivery work',
  '96': 'Other'},
 'P6#1': {'0': '0', '1': '1'},
 'P6#2': {'0': '0', '1': '1'},
 'P6#96': {'0': '0', '1': '1'},
 'P7_1': {'1': '1 Never',
  '2': '2',
  '3': '3',
  '4': '4',
  '5': '5 (Almost) always'},
 'P7_2': {'1': '1 Never',
  '2': '2',
  '3': '3',
  '4': '4',
  '5': '5 (Almost) always'},
 'P7_3': {'1': '1 Never',
  '2': '2',
  '3': '3',
  '4': '4',
  '5': '5 (Almost) always'},
 'P7_4': {'1': '1 Never',
  '2': '2',
  '3': '3',
  '4': '4',
  '5': '5 (Almost) always'},
 'P7_5': {'1': '1 Never',
  '2': '2',
  '3': '3',
  '4': '4',
  '5': '5 (Almost) always'},
 'P7_6': {'1': '1 Never',
  '2': '2',
  '3': '3',
  '4': '4',
  '5': '5 (Almost) always'},
 'P8#1': {'0': '0', '1': '1'},
 'P8#2': {'0': '0', '1': '1'},
 'P8#3': {'0': '0', '1': '1'},
 'P8#97': {'0': '0', '1': '1'},
 'P9#1': {'0': '0', '1': '1'},
 'P9#2': {'0': '0', '1': '1'},
 'P9#3': {'0': '0', '1': '1'},
 'P9#4': {'0': '0', '1': '1'},
 'P9#5': {'0': '0', '1': '1'},
 'P9#6': {'0': '0', '1': '1'},
 'P9#7': {'0': '0', '1': '1'},
 'P9#8': {'0': '0', '1': '1'},
 'P9#9': {'0': '0', '1': '1'},
 'P9#10': {'0': '0', '1': '1'},
 'P9#11': {'0': '0', '1': '1'},
 'P9#12': {'0': '0', '1': '1'},
 'P9#96': {'0': '0', '1': '1'},
 'P10_1': {'1': '1 Not at all satisfied',
  '2': '2',
  '3': '3',
  '4': '4',
  '5': '5 Completely satisfied'},
 'P10_2': {'1': '1 Not at all satisfied',
  '2': '2',
  '3': '3',
  '4': '4',
  '5': '5 Completely satisfied'},
 'P10_3': {'1': '1 Not at all satisfied',
  '2': '2',
  '3': '3',
  '4': '4',
  '5': '5 Completely satisfied'},
 'P10_4': {'1': '1 Not at all satisfied',
  '2': '2',
  '3': '3',
  '4': '4',
  '5': '5 Completely satisfied'},
 'P11_1': {'1': '1 Not at all satisfied',
  '2': '2',
  '3': '3',
  '4': '4',
  '5': '5 Completely satisfied'},
 'P11_2': {'1': '1 Not at all satisfied',
  '2': '2',
  '3': '3',
  '4': '4',
  '5': '5 Completely satisfied'},
 'P11_3': {'1': '1 Not at all satisfied',
  '2': '2',
  '3': '3',
  '4': '4',
  '5': '5 Completely satisfied'},
 'P11_4': {'1': '1 Not at all satisfied',
  '2': '2',
  '3': '3',
  '4': '4',
  '5': '5 Completely satisfied'},
 'P12_1': {'1': '1 Not at all satisfied',
  '2': '2',
  '3': '3',
  '4': '4',
  '5': '5 Completely satisfied'},
 'P12_2': {'1': '1 Not at all satisfied',
  '2': '2',
  '3': '3',
  '4': '4',
  '5': '5 Completely satisfied'},
 'P12_3': {'1': '1 Not at all satisfied',
  '2': '2',
  '3': '3',
  '4': '4',
  '5': '5 Completely satisfied'},
 'P12_4': {'1': '1 Not at all satisfied',
  '2': '2',
  '3': '3',
  '4': '4',
  '5': '5 Completely satisfied'},
 'P13': {'1': 'Always', '2': 'Most times', '3': 'Sometimes', '4': 'Never'},
 'P14#1': {'0': '0', '1': '1'},
 'P14#2': {'0': '0', '1': '1'},
 'P14#3': {'0': '0', '1': '1'},
 'P14#4': {'0': '0', '1': '1'},
 'P14#5': {'0': '0', '1': '1'},
 'P14#6': {'0': '0', '1': '1'},
 'P14#7': {'0': '0', '1': '1'},
 'P14#8': {'0': '0', '1': '1'},
 'P14#9': {'0': '0', '1': '1'},
 'P14#10': {'0': '0', '1': '1'},
 'P14#11': {'0': '0', '1': '1'},
 'P14#96': {'0': '0', '1': '1'},
 'P15_1': {'1': '1 Disagree', '2': '2', '3': '3', '4': '4', '5': '5 Agree'},
 'P15_2': {'1': '1 Disagree', '2': '2', '3': '3', '4': '4', '5': '5 Agree'},
 'P15_3': {'1': '1 Disagree', '2': '2', '3': '3', '4': '4', '5': '5 Agree'},
 'P15_4': {'1': '1 Disagree', '2': '2', '3': '3', '4': '4', '5': '5 Agree'},
 'P15_5': {'1': '1 Disagree', '2': '2', '3': '3', '4': '4', '5': '5 Agree'},
 'P15_6': {'1': '1 Disagree', '2': '2', '3': '3', '4': '4', '5': '5 Agree'},
 'P15_7': {'1': '1 Disagree', '2': '2', '3': '3', '4': '4', '5': '5 Agree'},
 'P15_8': {'1': '1 Disagree', '2': '2', '3': '3', '4': '4', '5': '5 Agree'},
 'P15_9': {'1': '1 Disagree', '2': '2', '3': '3', '4': '4', '5': '5 Agree'},
 'P15_10': {'1': '1 Disagree', '2': '2', '3': '3', '4': '4', '5': '5 Agree'},
 'P16': {'1': 'Simple motorcyclist jacket',
  '2': 'Jacket with integrated (built-in) protectors',
  '3': 'Jacket with integrated (built-in) inflatable protectors',
  '96': 'Other'},
 'P17': {'1': 'Always', '2': 'Most times', '3': 'Sometimes', '4': 'Never'},
 'P18#1': {'0': '0', '1': '1'},
 'P18#2': {'0': '0', '1': '1'},
 'P18#3': {'0': '0', '1': '1'},
 'P18#4': {'0': '0', '1': '1'},
 'P18#5': {'0': '0', '1': '1'},
 'P18#6': {'0': '0', '1': '1'},
 'P18#7': {'0': '0', '1': '1'},
 'P18#8': {'0': '0', '1': '1'},
 'P18#9': {'0': '0', '1': '1'},
 'P18#10': {'0': '0', '1': '1'},
 'P18#96': {'0': '0', '1': '1'},
 'P19_1': {'1': '1 Disagree', '2': '2', '3': '3', '4': '4', '5': '5 Agree'},
 'P19_2': {'1': '1 Disagree', '2': '2', '3': '3', '4': '4', '5': '5 Agree'},
 'P19_3': {'1': '1 Disagree', '2': '2', '3': '3', '4': '4', '5': '5 Agree'},
 'P19_4': {'1': '1 Disagree', '2': '2', '3': '3', '4': '4', '5': '5 Agree'},
 'P19_5': {'1': '1 Disagree', '2': '2', '3': '3', '4': '4', '5': '5 Agree'},
 'P19_6': {'1': '1 Disagree', '2': '2', '3': '3', '4': '4', '5': '5 Agree'},
 'P19_7': {'1': '1 Disagree', '2': '2', '3': '3', '4': '4', '5': '5 Agree'},
 'P19_8': {'1': '1 Disagree', '2': '2', '3': '3', '4': '4', '5': '5 Agree'},
 'P19_9': {'1': '1 Disagree', '2': '2', '3': '3', '4': '4', '5': '5 Agree'},
 'P19_10': {'1': '1 Disagree', '2': '2', '3': '3', '4': '4', '5': '5 Agree'},
 'P20#1': {'0': '0', '1': '1'},
 'P20#2': {'0': '0', '1': '1'},
 'P20#3': {'0': '0', '1': '1'},
 'P20#4': {'0': '0', '1': '1'},
 'P20#96': {'0': '0', '1': '1'},
 'P21#1': {'0': '0', '1': '1'},
 'P21#2': {'0': '0', '1': '1'},
 'P21#3': {'0': '0', '1': '1'},
 'P21#4': {'0': '0', '1': '1'},
 'P22': {'1': 'At least once a day',
  '2': 'At least once a week',
  '3': 'At least once a month',
  '4': 'At least once a year'},
 'P23': {'1': 'Commuting to work',
  '2': 'For recreation / as a hobby',
  '3': 'Shopping, or running errands',
  '4': 'For delivery work',
  '96': 'Other'},
 'P24': {'1': 'Commuting to work',
  '2': 'For recreation / as a hobby',
  '3': 'Shopping, or running errands',
  '4': 'For delivery work',
  '96': 'Other'},
 'P25#1': {'0': '0', '1': '1'},
 'P25#2': {'0': '0', '1': '1'},
 'P25#3': {'0': '0', '1': '1'},
 'P25#4': {'0': '0', '1': '1'},
 'P26_1': {'1': '1 Never',
  '2': '2',
  '3': '3',
  '4': '4',
  '5': '5 (Almost) always'},
 'P26_2': {'1': '1 Never',
  '2': '2',
  '3': '3',
  '4': '4',
  '5': '5 (Almost) always'},
 'P26_3': {'1': '1 Never',
  '2': '2',
  '3': '3',
  '4': '4',
  '5': '5 (Almost) always'},
 'P26_4': {'1': '1 Never',
  '2': '2',
  '3': '3',
  '4': '4',
  '5': '5 (Almost) always'},
 'P26_5': {'1': '1 Never',
  '2': '2',
  '3': '3',
  '4': '4',
  '5': '5 (Almost) always'},
 'P26_6': {'1': '1 Never',
  '2': '2',
  '3': '3',
  '4': '4',
  '5': '5 (Almost) always'},
 'P26_7': {'1': '1 Never',
  '2': '2',
  '3': '3',
  '4': '4',
  '5': '5 (Almost) always'},
 'P27#1': {'0': '0', '1': '1'},
 'P27#2': {'0': '0', '1': '1'},
 'P27#97': {'0': '0', '1': '1'},
 'P28#1': {'0': '0', '1': '1'},
 'P28#2': {'0': '0', '1': '1'},
 'P28#3': {'0': '0', '1': '1'},
 'P28#4': {'0': '0', '1': '1'},
 'P28#5': {'0': '0', '1': '1'},
 'P28#6': {'0': '0', '1': '1'},
 'P28#7': {'0': '0', '1': '1'},
 'P28#8': {'0': '0', '1': '1'},
 'P28#9': {'0': '0', '1': '1'},
 'P28#10': {'0': '0', '1': '1'},
 'P28#11': {'0': '0', '1': '1'},
 'P28#12': {'0': '0', '1': '1'},
 'P28#13': {'0': '0', '1': '1'},
 'P28#96': {'0': '0', '1': '1'},
 'P29_1': {'1': '1 Not at all satisfied',
  '2': '2',
  '3': '3',
  '4': '4',
  '5': '5 Completely satisfied'},
 'P29_2': {'1': '1 Not at all satisfied',
  '2': '2',
  '3': '3',
  '4': '4',
  '5': '5 Completely satisfied'},
 'P29_3': {'1': '1 Not at all satisfied',
  '2': '2',
  '3': '3',
  '4': '4',
  '5': '5 Completely satisfied'},
 'P29_4': {'1': '1 Not at all satisfied',
  '2': '2',
  '3': '3',
  '4': '4',
  '5': '5 Completely satisfied'},
 'P30_1': {'1': '1 Not at all satisfied',
  '2': '2',
  '3': '3',
  '4': '4',
  '5': '5 Completely satisfied'},
 'P30_2': {'1': '1 Not at all satisfied',
  '2': '2',
  '3': '3',
  '4': '4',
  '5': '5 Completely satisfied'},
 'P30_3': {'1': '1 Not at all satisfied',
  '2': '2',
  '3': '3',
  '4': '4',
  '5': '5 Completely satisfied'},
 'P30_4': {'1': '1 Not at all satisfied',
  '2': '2',
  '3': '3',
  '4': '4',
  '5': '5 Completely satisfied'},
 'P31': {'1': 'Always', '2': 'Most times', '3': 'Sometimes', '4': 'Never'},
 'P32#1': {'0': '0', '1': '1'},
 'P32#2': {'0': '0', '1': '1'},
 'P32#3': {'0': '0', '1': '1'},
 'P32#4': {'0': '0', '1': '1'},
 'P32#5': {'0': '0', '1': '1'},
 'P32#6': {'0': '0', '1': '1'},
 'P32#7': {'0': '0', '1': '1'},
 'P32#8': {'0': '0', '1': '1'},
 'P32#9': {'0': '0', '1': '1'},
 'P32#10': {'0': '0', '1': '1'},
 'P32#11': {'0': '0', '1': '1'},
 'P32#12': {'0': '0', '1': '1'},
 'P32#96': {'0': '0', '1': '1'},
 'P33_1': {'1': '1 Disagree', '2': '2', '3': '3', '4': '4', '5': '5 Agree'},
 'P33_2': {'1': '1 Disagree', '2': '2', '3': '3', '4': '4', '5': '5 Agree'},
 'P33_3': {'1': '1 Disagree', '2': '2', '3': '3', '4': '4', '5': '5 Agree'},
 'P33_4': {'1': '1 Disagree', '2': '2', '3': '3', '4': '4', '5': '5 Agree'},
 'P33_5': {'1': '1 Disagree', '2': '2', '3': '3', '4': '4', '5': '5 Agree'},
 'P33_6': {'1': '1 Disagree', '2': '2', '3': '3', '4': '4', '5': '5 Agree'},
 'P33_7': {'1': '1 Disagree', '2': '2', '3': '3', '4': '4', '5': '5 Agree'},
 'P33_8': {'1': '1 Disagree', '2': '2', '3': '3', '4': '4', '5': '5 Agree'},
 'P33_9': {'1': '1 Disagree', '2': '2', '3': '3', '4': '4', '5': '5 Agree'},
 'P33_10': {'1': '1 Disagree', '2': '2', '3': '3', '4': '4', '5': '5 Agree'},
 'P33_11': {'1': '1 Disagree', '2': '2', '3': '3', '4': '4', '5': '5 Agree'},
 'P33_12': {'1': '1 Disagree', '2': '2', '3': '3', '4': '4', '5': '5 Agree'},
 'P34': {'1': 'Normal helmet',
  '2': 'Inflatable helmet',
  '3': 'Foldable (non-inflatable) helmet',
  '4': 'Head Airbag',
  '96': 'Other'},
 'P35#1': {'0': '0', '1': '1'},
 'P35#2': {'0': '0', '1': '1'},
 'P36': {'1': 'At least once a day',
  '2': 'At least once a week',
  '3': 'At least once a month',
  '4': 'At least once a year'},
 'P37': {'1': 'Commuting to work',
  '2': 'For recreation / as a hobby',
  '3': 'Shopping, or running errands',
  '4': 'For delivery work',
  '96': 'Other'},
 'P38_1': {'1': '1 Never',
  '2': '2',
  '3': '3',
  '4': '4',
  '5': '5 (Almost) always'},
 'P38_2': {'1': '1 Never',
  '2': '2',
  '3': '3',
  '4': '4',
  '5': '5 (Almost) always'},
 'P38_3': {'1': '1 Never',
  '2': '2',
  '3': '3',
  '4': '4',
  '5': '5 (Almost) always'},
 'P38_4': {'1': '1 Never',
  '2': '2',
  '3': '3',
  '4': '4',
  '5': '5 (Almost) always'},
 'P38_5': {'1': '1 Never',
  '2': '2',
  '3': '3',
  '4': '4',
  '5': '5 (Almost) always'},
 'P38_6': {'1': '1 Never',
  '2': '2',
  '3': '3',
  '4': '4',
  '5': '5 (Almost) always'},
 'P39#1': {'0': '0', '1': '1'},
 'P39#2': {'0': '0', '1': '1'},
 'P39#97': {'0': '0', '1': '1'},
 'P40#1': {'0': '0', '1': '1'},
 'P40#2': {'0': '0', '1': '1'},
 'P40#3': {'0': '0', '1': '1'},
 'P40#4': {'0': '0', '1': '1'},
 'P40#5': {'0': '0', '1': '1'},
 'P40#6': {'0': '0', '1': '1'},
 'P40#7': {'0': '0', '1': '1'},
 'P40#8': {'0': '0', '1': '1'},
 'P40#9': {'0': '0', '1': '1'},
 'P40#10': {'0': '0', '1': '1'},
 'P40#11': {'0': '0', '1': '1'},
 'P40#12': {'0': '0', '1': '1'},
 'P40#13': {'0': '0', '1': '1'},
 'P40#14': {'0': '0', '1': '1'},
 'P40#96': {'0': '0', '1': '1'},
 'P41_1': {'1': '1 Not at all satisfied',
  '2': '2',
  '3': '3',
  '4': '4',
  '5': '5 Completely satisfied'},
 'P41_2': {'1': '1 Not at all satisfied',
  '2': '2',
  '3': '3',
  '4': '4',
  '5': '5 Completely satisfied'},
 'P41_3': {'1': '1 Not at all satisfied',
  '2': '2',
  '3': '3',
  '4': '4',
  '5': '5 Completely satisfied'},
 'P41_4': {'1': '1 Not at all satisfied',
  '2': '2',
  '3': '3',
  '4': '4',
  '5': '5 Completely satisfied'},
 'P42_1': {'1': '1 Not at all satisfied',
  '2': '2',
  '3': '3',
  '4': '4',
  '5': '5 Completely satisfied'},
 'P42_2': {'1': '1 Not at all satisfied',
  '2': '2',
  '3': '3',
  '4': '4',
  '5': '5 Completely satisfied'},
 'P42_3': {'1': '1 Not at all satisfied',
  '2': '2',
  '3': '3',
  '4': '4',
  '5': '5 Completely satisfied'},
 'P42_4': {'1': '1 Not at all satisfied',
  '2': '2',
  '3': '3',
  '4': '4',
  '5': '5 Completely satisfied'},
 'P43': {'1': 'Always', '2': 'Most times', '3': 'Sometimes', '4': 'Never'},
 'P44#1': {'0': '0', '1': '1'},
 'P44#2': {'0': '0', '1': '1'},
 'P44#3': {'0': '0', '1': '1'},
 'P44#4': {'0': '0', '1': '1'},
 'P44#5': {'0': '0', '1': '1'},
 'P44#6': {'0': '0', '1': '1'},
 'P44#7': {'0': '0', '1': '1'},
 'P44#8': {'0': '0', '1': '1'},
 'P44#9': {'0': '0', '1': '1'},
 'P44#10': {'0': '0', '1': '1'},
 'P44#11': {'0': '0', '1': '1'},
 'P44#96': {'0': '0', '1': '1'},
 'P45_1': {'1': '1 Disagree', '2': '2', '3': '3', '4': '4', '5': '5 Agree'},
 'P45_2': {'1': '1 Disagree', '2': '2', '3': '3', '4': '4', '5': '5 Agree'},
 'P45_3': {'1': '1 Disagree', '2': '2', '3': '3', '4': '4', '5': '5 Agree'},
 'P45_4': {'1': '1 Disagree', '2': '2', '3': '3', '4': '4', '5': '5 Agree'},
 'P45_5': {'1': '1 Disagree', '2': '2', '3': '3', '4': '4', '5': '5 Agree'},
 'P45_6': {'1': '1 Disagree', '2': '2', '3': '3', '4': '4', '5': '5 Agree'},
 'P45_7': {'1': '1 Disagree', '2': '2', '3': '3', '4': '4', '5': '5 Agree'},
 'P45_8': {'1': '1 Disagree', '2': '2', '3': '3', '4': '4', '5': '5 Agree'},
 'P45_9': {'1': '1 Disagree', '2': '2', '3': '3', '4': '4', '5': '5 Agree'},
 'P45_10': {'1': '1 Disagree', '2': '2', '3': '3', '4': '4', '5': '5 Agree'},
 'P45_11': {'1': '1 Disagree', '2': '2', '3': '3', '4': '4', '5': '5 Agree'},
 'P45_12': {'1': '1 Disagree', '2': '2', '3': '3', '4': '4', '5': '5 Agree'},
 'P46': {'1': 'Normal helmet',
  '2': 'Inflatable helmet',
  '3': 'Foldable (non-inflatable) helmet',
  '4': 'Head Airbag',
  '96': 'Other'},
 'P47': {'1': 'Yes', '2': 'No'},
 'P48': {'1': 'Very interested',
  '2': 'Somewhat interested',
  '3': 'Neutral',
  '4': 'Somewhat uninterested',
  '5': 'Not interested at all'},
 'P49#1': {'0': '0', '1': '1'},
 'P49#2': {'0': '0', '1': '1'},
 'P49#3': {'0': '0', '1': '1'},
 'P49#4': {'0': '0', '1': '1'},
 'P49#5': {'0': '0', '1': '1'},
 'P49#6': {'0': '0', '1': '1'},
 'P49#96': {'0': '0', '1': '1'},
 'P50#1': {'0': '0', '1': '1'},
 'P50#2': {'0': '0', '1': '1'},
 'P50#3': {'0': '0', '1': '1'},
 'P50#4': {'0': '0', '1': '1'},
 'P50#96': {'0': '0', '1': '1'},
 'P51R_1': {'1': 'Daily commute',
  '2': 'Using a bike-sharing or scooter-sharing system',
  '3': 'Cycling at night or in low-visibility conditions',
  '4': 'Recreational or leisure cycling',
  '5': 'Long-distance cycling or touring',
  '6': 'Cycling in another city as a tourist'},
 'P51R_2': {'1': 'Daily commute',
  '2': 'Using a bike-sharing or scooter-sharing system',
  '3': 'Cycling at night or in low-visibility conditions',
  '4': 'Recreational or leisure cycling',
  '5': 'Long-distance cycling or touring',
  '6': 'Cycling in another city as a tourist'},
 'P51R_3': {'1': 'Daily commute',
  '2': 'Using a bike-sharing or scooter-sharing system',
  '3': 'Cycling at night or in low-visibility conditions',
  '4': 'Recreational or leisure cycling',
  '5': 'Long-distance cycling or touring',
  '6': 'Cycling in another city as a tourist'},
 'P51R_4': {'1': 'Daily commute',
  '2': 'Using a bike-sharing or scooter-sharing system',
  '3': 'Cycling at night or in low-visibility conditions',
  '4': 'Recreational or leisure cycling',
  '5': 'Long-distance cycling or touring',
  '6': 'Cycling in another city as a tourist'},
 'P51R_5': {'1': 'Daily commute',
  '2': 'Using a bike-sharing or scooter-sharing system',
  '3': 'Cycling at night or in low-visibility conditions',
  '4': 'Recreational or leisure cycling',
  '5': 'Long-distance cycling or touring',
  '6': 'Cycling in another city as a tourist'},
 'P51R_6': {'1': 'Daily commute',
  '2': 'Using a bike-sharing or scooter-sharing system',
  '3': 'Cycling at night or in low-visibility conditions',
  '4': 'Recreational or leisure cycling',
  '5': 'Long-distance cycling or touring',
  '6': 'Cycling in another city as a tourist'},
 'P53': {'1': 'Very safe',
  '2': 'Somewhat safe',
  '3': 'Neutral',
  '4': 'Somewhat unsafe',
  '5': 'Very unsafe'},
 'P55': {'1': 'Yes', '2': 'No'},
 'P56': {'1': 'Very interested',
  '2': 'Somewhat interested',
  '3': 'Neutral',
  '4': 'Somewhat uninterested',
  '5': 'Not interested at all'},
 'P57#1': {'0': '0', '1': '1'},
 'P57#2': {'0': '0', '1': '1'},
 'P57#3': {'0': '0', '1': '1'},
 'P57#4': {'0': '0', '1': '1'},
 'P57#5': {'0': '0', '1': '1'},
 'P57#6': {'0': '0', '1': '1'},
 'P57#96': {'0': '0', '1': '1'},
 'P58#1': {'0': '0', '1': '1'},
 'P58#2': {'0': '0', '1': '1'},
 'P58#3': {'0': '0', '1': '1'},
 'P58#4': {'0': '0', '1': '1'},
 'P58#96': {'0': '0', '1': '1'},
 'P59R_1': {'1': 'Daily commute',
  '2': 'Using a bike-sharing or scooter-sharing system',
  '3': 'Cycling at night or in low-visibility conditions',
  '4': 'Recreational or leisure cycling',
  '5': 'Long-distance cycling or touring',
  '6': 'Cycling in another city as a tourist'},
 'P59R_2': {'1': 'Daily commute',
  '2': 'Using a bike-sharing or scooter-sharing system',
  '3': 'Cycling at night or in low-visibility conditions',

## 2. Decode numeric values in Labels

In [50]:
decoded_df = labels_df.copy()

for column in decoded_df.columns:
    if column in code_dict:
        decoded_df[column] = decoded_df[column].map(
            lambda x: code_dict[column].get(x, x)
        )
decoded_df.head()

,key,numericalId,accessCount,startTime,endTime,duration,status,type,SAMPLE,CodPanelista,...,P84_cod3,P84_cod4,P84_cod5,P84_cod6,P91_cod1,P91_cod2,P91_cod3,P91_cod4,P91_cod5,P91_cod6
0,2fd1e655-a94d-4a91-a4fa-ed22b097ce62,684173892,1,2025-09-22 12:17:19,2025-09-22 12:32:20,900,end,complete,INTERNAL,01519d71455139b9,...,NaN,NaN,NaN,NaN,Protection against specific accidents (protect...,NaN,NaN,NaN,NaN,NaN
1,7da18c0c-caa8-4c5e-a5de-47f0805bb06e,684295712,1,2025-09-23 06:00:19,2025-09-23 06:15:05,886,end,complete,INTERNAL,02082c28ac6c270d,...,NaN,NaN,NaN,NaN,I don't like the product (don't need this prod...,NaN,NaN,NaN,NaN,NaN
2,f4fe2017-372a-4d5b-8a7c-6604cc560ec9,684182100,2,2025-09-22 13:36:32,2025-09-23 08:55:05,1293,end,complete,INTERNAL,0248c65078193632,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,224d885a-7942-417d-805d-82060fe5f206,684297408,3,2025-09-23 06:40:22,2025-09-23 06:49:51,578,end,complete,INTERNAL,0371c3d2680a5100,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,e18389a7-a1d4-4697-a0af-e9776552cb2b,684296611,1,2025-09-23 06:21:05,2025-09-23 06:44:30,1405,end,complete,INTERNAL,03af3ddf6752205f,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## 3. Rename columns

In [51]:
# Creamos el mapa de nombres: {"Q1": "¿Cuál es su edad?"}
names_dict = dict(zip(variables_df['Variable'], variables_df['Etiqueta']))

# Renombramos todo el DataFrame de una vez
decoded_df.rename(columns=names_dict, inplace=True)

# Processing for R

## 1. Clean dictionaries

In [52]:
codes_df['Variable'] = codes_df['Variable'].astype(str).str.strip()
variables_df['Variable'] = variables_df['Variable'].astype(str).str.strip()

## 2. Treat Variables

In [53]:
cols_nominales = variables_df[variables_df['Nivel de medición'] == 'Nominal']['Variable'].unique()

for col in labels_df.columns:
    if col in cols_nominales:
        # Buscamos el mapeo para esta columna
        mapping = codes_df[codes_df['Variable'] == col]
        if not mapping.empty:
            map_dict = dict(zip(mapping['Variable'], mapping['Label']))
            labels_df[col] = labels_df[col].map(map_dict).fillna(labels_df[col])

In [54]:
cols_escala = variables_df[variables_df['Nivel de medición'] == 'Escala']['Variable'].unique()
for col in cols_escala:
    if col in labels_df.columns:
        labels_df[col] = pd.to_numeric(labels_df[col], errors='coerce')

## 3. Naming R

In [55]:
def clean_header_r(text):
    # Eliminar acentos
    text = text.replace('á', 'a').replace('é', 'e').replace('í', 'i').replace('ó', 'o').replace('ú', 'u')
    # Quitar caracteres especiales y dejar solo letras, números y espacios
    text = re.sub(r'[^a-zA-Z0-9\s]', '', text)
    # Reemplazar espacios por puntos (estándar clásico de R)
    text = text.strip().replace(" ", ".")
    return text[:60] # Acortar para que sea manejable

# Crear el diccionario de nombres: { 'Q1': 'Nivel.de.satisfaccion...' }
name_mapping = dict(zip(variables_df['Variable'], variables_df['Etiqueta'].apply(clean_header_r)))
labels_df.rename(columns=name_mapping, inplace=True)

# Save data

In [59]:
# decoded_df.to_csv(PROCESSED_DATA_DIR/"survey_clean_powerbi.csv", index=False)

decoded_df.to_excel(PROCESSED_DATA_DIR/"IMPROVA_clean_for_powerbi.xlsx", index=False)


labels_df.to_csv(PROCESSED_DATA_DIR/'IMPROVA_clean_for_R.csv', index=False, encoding='utf-8')